config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'links#index'
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :update_sanitized_params, if: :devise_controller?
def update_sanitized_params
devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if flash[:error] %>
  <div id="error">
  <%= flash[:error] %>
  </div>
  <% end %>
  <div id="container">
  <div id="user_status">
  <% if user_signed_in? %>
  Welcome <%= current_user.email %>! Not you?
  <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path %> or
  <%= link_to "Sign in", new_user_session_path %>.
  <% end %>
  </div>
  <%= yield %>
  </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p>
    <strong>Name:</strong>
    <%= link.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= link.url %>
  </p>

</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<div id="links">
  <% @links.each do |link| %>
    <%= render link %>
    <p>
      <%= link_to "Show this link", link %>
    </p>
  <% end %>
</div>

<%= link_to "New link", new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "Back to links", links_path %>

  <%= button_to "Destroy this link", @link, method: :delete %>
</div>